version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - LDAP_SERVER=ldaps://ldap.google.com
      - SEARCH_BASE=ou=Users,dc=visiquate,dc=com
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs:ro
      - ./coverage:/app/coverage
    working_dir: /app