services:
  birthdays-to-slack:
    image: ghcr.io/brentley/birthdays-to-slack:latest
    container_name: birthdays-to-slack
    ports:
      - "5000:5000"
    environment:
      - LDAP_SERVER=ldaps://ldap.google.com
      - SEARCH_BASE=ou=Users,dc=visiquate,dc=com
      - ICS_URL=${ICS_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - FLASK_ENV=production
      - PORT=5000
      - SLACK_NOTIFICATIONS_ENABLED=${SLACK_NOTIFICATIONS_ENABLED:-false}
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs:ro
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.scope=birthdays-to-slack"

  watchtower:
    image: containrrr/watchtower
    container_name: birthdays-to-slack-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_SCOPE=birthdays-to-slack
      # Only enable email notifications if configured
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL_FROM:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_EMAIL_SERVER:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_EMAIL_PORT:-587}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_EMAIL_USER:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_EMAIL_PASSWORD:-}
    command: --interval 300 --cleanup --scope birthdays-to-slack

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: birthdays-to-slack-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - birthdays-to-slack
    environment:
      - NO_AUTOUPDATE=true